name = "JuliaDataStructures"
uuid = "80a7cba2-cb72-4aab-b269-45c1f1ff46d0"
authors = ["Darren Colby <dscolby17@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
